### ISSUE TITLE
Translation does not seem to work any more

### ISSUE THREAD

**Issue by grandeljay** [soerenuhrbach/vscode-deepl#45]
When attempting to translate text (i. e. from German to Spanish), I receive the success message but the text remains untranslated.

![image](https://github.com/soerenuhrbach/vscode-deepl/assets/45571053/eb8d68c9-2ea9-43e1-b555-4f5f90b36a63)

My User `settings.json`:
```json
{
    "deepl.apiKey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "deepl.defaultSourceLanguage": "DE",
    "deepl.defaultTargetLanguage": "EN-GB",
    "deepl.formality": "more",
    "deepl.splitSentences": "1",
    "deepl.tagHandling": "html",
    "deepl.translationMode": "Replace",
    "deepl.usePro": true,
}
```
I am using a DeepL Pro API key.

Any idea why?

**Comment by grandeljay** [comment]
Version 1.0.7 is the last working Version for me.

**Comment by soerenuhrbach** [comment]
Hi @grandeljay,

I just released a newer version (1.0.12), which includes a few bug fixes. Please check this out.
If the error occurs again, check the Extension-Output and provide it in this issue.

<img width="1622" alt="image" src="https://github.com/soerenuhrbach/vscode-deepl/assets/18682112/6df70911-93fb-4a59-9202-c2a773374cc3">

**Comment by grandeljay** [comment]
Thanks for the update! I didn't get around to testing earlier but now I got this:
![image](https://github.com/soerenuhrbach/vscode-deepl/assets/45571053/d66fe9bb-8c08-4218-8b0b-60ec775ac3e2)

I checked my settings and can't find a field for the API key any more using the UI. In my `User/settings.json` I found it but it's greyed out, as if it's no longer used:
![image](https://github.com/soerenuhrbach/vscode-deepl/assets/45571053/4a146709-402c-45e5-be5f-357d2766fd72)

**Comment by soerenuhrbach** [comment]
@grandeljay It's correct, that the api key is greyed out, because the api key is now stored in vscode's secret store.

The api keys should have been migrated automatically.. I don't know why it didn't worked in your case.

Please try to set your api key again using the command "DeepL: Configure extension".

**Comment by grandeljay** [comment]
That seemed to help, thanks! There's more though... 

When I select Translate From... To... I have the following selection:
![image](https://github.com/soerenuhrbach/vscode-deepl/assets/45571053/d9e641d3-d5fc-4dc1-bf4c-7b867b3066db)
This already looks unusual to me because en-GB and en-US are usually only available as target languages, not as source languages.

I then get this response, which again seems unusual to me, since my target language (German) _does_ support formality (right?)
![image](https://github.com/soerenuhrbach/vscode-deepl/assets/45571053/87bad703-b4de-4d1e-9b19-c4d7dec00b81)

So I remove
```json
{
  "deepl.formality": "more",
}
```
from my settings and then this warning appears:
![image](https://github.com/soerenuhrbach/vscode-deepl/assets/45571053/ef06090e-14eb-4be6-a9a5-27fe4da95bab)
Which also seems odd, since my source language was `en-GB` and my target language was `de`, not vice versa (as seen on this warning)

It all feels upside-down to me. Do you have any more ideas what I could try? Do you think uninstalling the extensions and reinstalling it, would help?

Thanks for all the help so far!

**Comment by soerenuhrbach** [comment]
If you try to translate "Hello World" with the source language "de" to "en-us" or "en-gb", then deepl returns the same texts as before. Because the original text was not German, but already English.  

To make these cases visible, the extensions shows these warnings to give you the chance to resolve the issue (in case you have the from source language from previous translations).

It should work if you have the correct source language configured.

----

I didn't knew, that a exception is raised, if the formality is not available for the source language - I'll improve the behaviour and implement a fallback without the configured formality in case it didn't worked in first instance.

**Comment by soerenuhrbach** [comment]
Oh, you'r right. 
The prompt order has been changed with the last changes :/

The first prompt is now for the target language and the second prompt for the source language.
I think it was different before, because now the order does not match with the command name "Translate from ... to ...".
The correct command name should now be "Translate to ... from ...". 

I'll think about how I solve that! For now please try to select the target language first.

**Comment by soerenuhrbach** [comment]
@grandeljay Does it work now?

**Comment by grandeljay** [comment]
Oh right, sorry. Forgot to test. It seems to work now! Thanks! I guess I was simply confused by the different order of language selection.
