### ISSUE TITLE
Support for arabic lang!

### ISSUE THREAD

**Issue by HammadSaud** [soerenuhrbach/vscode-deepl#60]
DeepL supports Arabic lang, bu this extension is NOT!!

**Comment by soerenuhrbach** [comment]
Hi @HammadSaud,

All available languages are provided through the DeepL api. 
Currently the DeepL does not provide arabic, because it's not available for document translations. (see https://developers.deepl.com/docs/api-reference/languages)
As soon, as arabic will be delivered with this endpoint, it will be available in the extension.

**Comment by HammadSaud** [comment]
I think it's available because it's working just fine in WordPress with this plugin:

https://sa.wordpress.org/plugins/loco-translate/

**Comment by soerenuhrbach** [comment]
As the documentation says, the language won't be provided via the languages endpoint, so it can't be selected in the extension, since I didn't hardcode the languages. Instead of doing that now, I'll wait until the arabic language is fully supported.

> As of January 2024, Arabic (AR) is supported as a source and target language for [text translation](https://developers.deepl.com/docs/api-reference/translate), but it is not yet supported for [document translation](https://developers.deepl.com/docs/api-reference/document). Therefore, Arabic has not yet been added to the /languages endpoint. We will add Arabic to the /languages endpoint after document translation support is added.

Source: https://developers.deepl.com/docs/api-reference/languages
